# Generated by Django 6.0.4 on 2026-04-24 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='class_teacher',
            field=models.ForeignKey(limit_choices_to={'depart_id': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='web.userinfo', verbose_name='班主任'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='tech_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'depart_id__in': [6, 7]}, related_name='teach_classes', to='web.userinfo', verbose_name='任课老师'),
        ),
    ]
